language: julia
os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1 # latest stable 1+
  # - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email:
    on_success: never
    on_failure: never
